[tool.poetry]
name = "robot-vansah"
version = "0.0.1"
description = ""
authors = ["Shubham Mourya <shubham.mourya@testpoint.com.au>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
robotframework = "^7.0"
robotframework-seleniumlibrary = "^6.3.0"
requests = "^2.32.3"
# Security updates - explicit version constraints to fix vulnerabilities
urllib3 = "^2.6.0"  # Fixes CVE-2025-66471, CVE-2025-66418, CVE-2025-50181, CVE-2025-50182
h11 = "^0.16.0"     # Fixes GHSA-vqfr-h8mv-ghfj (malformed Chunked-Encoding)


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
